//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MMLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class AlbumCover
    {
        public int Id { get; set; }
        public byte[] AlbumCover1 { get; set; }
        public int AlbumId { get; set; }
    }
}
