/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package finalfractal;

import java.awt.Graphics;
import java.awt.Graphics2D;

/**
 *
 * @author faruk
 */
public class FinalFractalPanel extends javax.swing.JPanel {
    
    /**
     * assume panel is 200x200
     */
    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);
        Graphics2D g2d = (Graphics2D) g.create();
        // dege
        int edge = 280;
        // x,y point
        int x1 = 60;
        int y1 = 10;
        //center x,y
        int centerX = x1 + edge / 2;
        int centerY = y1 + edge / 2;

        //
        g2d.drawRect(x1, y1, edge, edge);
        drawSquareFractal(g2d, centerX, centerY,edge);

    }
    /**
     * method: drawSquareFractal
     */    
    private void drawSquareFractal(Graphics2D g2d, int centerX, int centerY, int edge) {
        if(edge < 10) return;
        
        //new edge
        edge = edge / 2;
        //new point (4 small square)
        int lTX =  centerX - edge * 3/4;
        int lTY =  centerY - edge * 3/4;
        int rTX =  centerX + edge * 3/4;
        int rTY =  centerY - edge * 3/4;        
        int lBX =  centerX - edge * 3/4;
        int lBY =  centerY + edge * 3/4;
        int rBX =  centerX + edge * 3/4;
        int rBY =  centerY + edge * 3/4; 
        
        //1. draw the center big square;
        g2d.drawLine(centerX-edge,centerY,centerX,centerY-edge);
        g2d.drawLine(centerX,centerY-edge,centerX+edge,centerY);
        g2d.drawLine(centerX+edge,centerY,centerX,centerY+edge);
        g2d.drawLine(centerX,centerY+edge,centerX-edge,centerY);
        
        //2. draw the small 4 square;
        int newEdge = edge/2;
  
        g2d.drawRect(lTX-newEdge/2, lTY-newEdge/2, newEdge, newEdge);
        g2d.drawRect(rTX-newEdge/2, rTY-newEdge/2, newEdge, newEdge);
        g2d.drawRect(lBX-newEdge/2, lBY-newEdge/2, newEdge, newEdge);
        g2d.drawRect(rBX-newEdge/2, rBY-newEdge/2, newEdge, newEdge);
        
        //3.Iteration
        drawSquareFractal(g2d, lTX, lTY, newEdge); 
        drawSquareFractal(g2d, rTX, rTY, newEdge);
        drawSquareFractal(g2d, lBX, lBY, newEdge);
        drawSquareFractal(g2d, rBX, rBY, newEdge);
    }

    /**
     * Creates new form FinalFractalPanel
     */
    public FinalFractalPanel() {
        //initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
